//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Документы
    {
        public int ID { get; set; }
        public int Клиент { get; set; }
        public Nullable<int> Страховой_полис { get; set; }
        public Nullable<int> Билет { get; set; }
        public Nullable<int> Виза { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
    }
}
