//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Тур { get; set; }
        public Nullable<int> Тип_питания { get; set; }
        public Nullable<int> Услуги { get; set; }
    
        public virtual Tours Tours { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Типы_питания Типы_питания { get; set; }
        public virtual Услуги Услуги1 { get; set; }
    }
}
