//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Клиенты()
        {
            this.Ваучеры = new HashSet<Ваучеры>();
            this.Документы1 = new HashSet<Документы>();
            this.Заявки = new HashSet<Заявки>();
            this.Отзывы_отелей = new HashSet<Отзывы_отелей>();
        }
    
        public int ID { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Год_рождения { get; set; }
        public Nullable<int> Документы { get; set; }
        public Nullable<System.DateTime> Дата_тура { get; set; }
        public string Предпочтения_тура { get; set; }
        public Nullable<int> Отель { get; set; }
        public Nullable<int> Верхняя_грань_стоимости { get; set; }
        public Nullable<int> Нижняя_грань_стоимости { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ваучеры> Ваучеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Документы> Документы1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
        public virtual Отели Отели { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отзывы_отелей> Отзывы_отелей { get; set; }
    }
}
