//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отзывы_отелей
    {
        public int ID { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Отель { get; set; }
        public Nullable<int> Количество_звёзд { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Отели Отели { get; set; }
    }
}
