//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туры
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отели()
        {
            this.Клиенты = new HashSet<Клиенты>();
            this.Отзывы_отелей = new HashSet<Отзывы_отелей>();
        }
    
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<int> Уровень_комфорта { get; set; }
        public string Страна { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Клиенты> Клиенты { get; set; }
        public virtual Страны Страны { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отзывы_отелей> Отзывы_отелей { get; set; }
    }
}
